adding required methods and functions for "__typename must be const" change
captbaritone/grats pull request #137
Opened 2024-03-25 11:29 UTC by Rash-Hit

Resolves #122 

This pr will add 
 - [ ] Required Method and function for  " __typename must be const" Change
 - [ ] Test Files 
 - [ ] Changes In Other Test Files 

 
Before - 

![image](https://github.com/captbaritone/grats/assets/73944177/af4259c6-7692-4c4b-8049-682a9e7a2b26)

After 

![image](https://github.com/captbaritone/grats/assets/73944177/8a9a1205-4f5f-4e0b-8de0-8c08549163c4)

Fix 

![image](https://github.com/captbaritone/grats/assets/73944177/725250b9-acfe-49c3-971c-22182c1113be)

--- 
@captbaritone  Please review , and let me know for the change's

2024-03-25 19:19 UTC, captbaritone commented
Nice work, this is looking great! Next steps would be:

1. Update the existing tests (unit and itegration) to not trigger this issue
2. Create new test fixtures which trigger each of these conditions
3. Update docs to always include `as const` (Running `pnpm run build` in the grats dir and `pnpm run grats` from within the website dir should uncover some of these, as it will rebuild many of the snippets) 
4. Update example projects to include `as const` (`pnpm run integration-tests` should uncover these)

Tips on running fixtures tests can be found here: https://github.com/captbaritone/grats/blob/main/CONTRIBUTING.md#automated-tests

2024-03-27 17:24 UTC, captbaritone requested changes
Looking good! A few comments about error messages.

Also, this would be a great candidate for a code action. I landed support for them yesterday: https://github.com/captbaritone/grats/commit/0b53e3df0c583e650dd409f182d1f82c1df1926c

If you'd like to add support for that as part of this change, you can see an example [here](https://github.com/captbaritone/grats/blob/bdbc112016461f33a547c50a2aad06c5a5fe6d31/src/Extractor.ts#L219). (you'll need to rebase)

Also happy to add this myself or have that be a followup PR.

Finally, can search through the `website` directory for instances of `__typename` and see if there are any changes that need to be made there?

2024-03-27 17:24 UTC, captbaritone commented on src/Extractor.ts
> +    if (node.initializer.type.typeName.escapedText !== "const") {
```suggestion
    if (node.initializer.type.typeName.escapedText !== ts.SyntaxKind.ConstKeyword) {
```

2024-03-27 17:24 UTC, captbaritone commented on src/Errors.ts
> +  return `Expected \`__typename\` property initializer to be an expression with a const assertion. For example: \`__typename = "MyType" as const\`. ${TYPENAME_CONTEXT}`;
A nice improvement we could make here is to pass the expected typename as an argument so that we use the expected typename instead of "MyType"

2024-03-27 17:24 UTC, captbaritone commented on src/Errors.ts
> +  return `Expected \`__typename\` property type to be a TypeReferenceNode. ${TYPENAME_CONTEXT}`;
I'd love to try to avoid using AST type names in error messages if possible. I don't think most developers know (or should need to know) what a `TypeReferenceNode` or `Identifier` are. Maybe we should just simplify this down to one error message that looks more like the one in `typeNameInitializeNotExpression` and use it for all of these new error cases?

2024-03-27 17:25 UTC, captbaritone commented
Also, can we make sure to have a fixture test for every error case? I don't think I see some of the new error messages represented in the test fixtures.

2024-03-28 09:48 UTC, Rash-Hit commented on src/Extractor.ts
> +    if (node.initializer.type.typeName.escapedText !== "const") {
I've tried this thing , but getting this error 
![image](https://github.com/captbaritone/grats/assets/73944177/d12ae260-4985-4ac4-b053-5e1e51f1c892)

and the reason is 
![image](https://github.com/captbaritone/grats/assets/73944177/5d730864-930f-4284-b2e5-ca01ad345122)

![image](https://github.com/captbaritone/grats/assets/73944177/e31f70da-292e-4677-aec9-1ae6fdbe2f9a)

2024-03-28 19:33 UTC, captbaritone commented on src/Extractor.ts
> +    if (node.initializer.type.typeName.escapedText !== "const") {
Interesting. I guess it doesn't parse `as const` as a keyword! Leaving this as a string is fine.

2024-03-31 07:39 UTC, Rash-Hit commented
@captbaritone . sir can you please review it and let me know for the required changes ..

2024-03-31 22:20 UTC, captbaritone commented
Thanks! I had some commits on main which I had to revert (unrelated to this PR) which meant I had to manually merge as https://github.com/captbaritone/grats/commit/1eed52344bd8061ceef7783170d9affcf42aea7c

You can see your commits (plus a few additions/and fixups) there.

2024-03-31 22:20 UTC, closed without merging